server:
  port: 8081
spring:
  application:
    name: felix
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 531978
  redis:
    host: 192.168.200.130
    port: 6379
    password: 531978
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 192.168.200.130 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: admin # 用户名
    password: admin # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
    # 异步confirm模式
    publisher-confirm-type: correlated
mybatis-plus:
  type-aliases-package: com.felix.entity # 别名扫描包
logging:
  level:
    com.felix: debug
